# Generated by Django 3.0 on 2019-12-29 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191217_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='created_product', to='core.Person', verbose_name='created by')),
                ('modified_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='modified_product', to='core.Person', verbose_name='modified by')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='price')),
                ('currency', models.CharField(max_length=15, verbose_name='currency')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('price', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='price')),
                ('currency', models.CharField(max_length=15, verbose_name='currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='created_shop', to='core.Person', verbose_name='created by')),
                ('modified_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='modified_shop', to='core.Person', verbose_name='modified by')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='shops', to='core.Person', verbose_name='owner')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('default_currency', models.CharField(max_length=15, verbose_name='currency')),
                ('value_increase', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='value increase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='created_shoppinglist', to='core.Person', verbose_name='created by')),
                ('modified_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='modified_shoppinglist', to='core.Person', verbose_name='modified by')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='shoppingLists', to='core.Shop', verbose_name='shop')),
                ('currency_used', models.CharField(max_length=15, verbose_name='currency used')),
                ('dolar_value', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='dolar value')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
                ('products', models.ManyToManyField(related_name='shoppingLists', related_query_name='shoppingList', through='core.ProductInfo', to='core.Product', verbose_name='products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='naturalness',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='ShoppingList',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ShoppingList'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shops', related_query_name='shop', to='core.Shop', verbose_name='shop'),
        ),
    ]
