# Generated by Django 3.0 on 2020-01-02 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def apply_user(apps, schema):
    User = apps.get_model('auth.User')
    u = User.objects.first()
    if u:
        Person = apps.get_model('core.person')
        Person.objects.update(created_by=u)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20191217_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_person', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.RunPython(apply_user, lambda *args, **kwargs: None)
    ]
